_format_version: "3.0"

services:
  - name: echo-server
    host: host.docker.outer
    # port: 4000
    protocol: http
    path: /echo
    routes:
      - name: localhost_echo_route
        paths:
        - /echo
        strip_path: true

upstreams:
- name: example_upstream
  targets:
    - target: 127.0.0.1:4000
      weight: 100
    - target: 127.0.0.1:4001
      weight: 100

plugins:
- name: rate-limiting
  config:
    minute: 50
    policy: local