# For more about API Authorization plugin : https://docs.konghq.com/hub/kong-inc/key-auth/

_format_version: "2.1"


services:
  - name: echo-server
    host: host.docker.internal
    port: 4000
    path: /echo
    routes:
      - name: localhost_echo_route
        paths:
        - /echo_server
        - /echo_server2
  - name: remote_server
    host: host.docker.internal
    port: 4000
    path: /remote
    routes:
     - name: localhost_remote_routee
       paths:
        - /remote_server
        - /remote_server2


# step 1:  Create consumer in Kong.
consumers:
  - username: rasel

# step: 2 Create ACLs for consumer
acls:
- consumer: rasel
  group: group1


# step 2: create key auth Credentials
keyauth_credentials:
- consumer: rasel
  ttl: 5
  tags:
    - example_tag
  key: rasel_api_key



plugins:
# step 3: Enable ACL plugin 
- name: acl
  config:
    # deny:
    # - group1
    allow: 
    - group1
    hide_groups_header: true

# step 4: Enable key auth plugin
- name: key-auth
  config:
    key_names:
    - apikey
    key_in_body: true
    key_in_header: true
    # key_in_query: falses 
    run_on_preflight: true


# Curl=>  curl -H "apikey: rasel_api_key" http://localhost:8000/echo_server