# For more about ratelimiting plugin : https://docs.konghq.com/hub/kong-inc/rate-limiting/how-to/basic-example/

_format_version: "3.0"



services:
  - name: echo-server
    host: host.docker.internal
    port: 4000
    path: /echo
    routes:
      - name: localhost_echo_route
        paths:
        - /echo_server
        - /echo_server2
  - name: remote_server
    host: host.docker.internal
    port: 4000
    path: /remote
    routes:
     - name: localhost_remote_routee
       paths:
        - /remote_server
        - /remote_server2


plugins:
- name: rate-limiting
  config:
   # second: 1
    hour: 10
    policy: local
    fault_tolerant: true
    hide_client_headers: false
    redis_ssl: false
    redis_ssl_verify: false


