# For more about ratelimiting plugin : https://docs.konghq.com/hub/kong-inc/ip-restriction/how-to/basic-example/

_format_version: "3.0"

services:
  - name: echo-server
    host: host.docker.internal
    port: 4000
    path: /echo
    routes:
      - name: localhost_echo_route
        paths:
        - /echo_server
        - /echo_server2
  - name: remote_server
    host: host.docker.internal
    port: 4000
    path: /remote
    routes:
     - name: localhost_remote_routee
       paths:
        - /remote_server
        - /remote_server2

# plugins
plugins:
- name: ip-restriction
  config:
    allow:
    - 143.1.0.0/24
    deny:
    - 103.156.176.91
    status: 401
    message: "your ip is not allowed😜"



